# Generated by Django 5.2.4 on 2025-09-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='book_covers/default_cover.jpg', null=True, upload_to='book_covers/'),
        ),
    ]
